### ISSUE TITLE
Using the plugin with MPLABX v5.35? 

### ISSUE THREAD

**Issue by esbon125** [lcgamboa/picsimlab_md#1]
Sorry for bothering, but I've been trying to use the plugin for MPLABX v5.35, and I couldn't. I read the documentation, and I downloaded the version of the plugin for v5.30, as it doesn't exist for v5.35, and I'm using the latest version of Picsimlab(installed through flatpak). I've allowed the tcp port 1234 through the firewall. It's imperative that the MPLABX version includes mpasm, and that's why I'm using v5.35, so basically I can start debugging the board with MPLABX, and I get this output from picsim output in MPLAB:
```picsim 
FileRegisters Memory size: 4096
Program Target Write ProgMem:32768 of 32768
Program Target Write ConfMem:14 of 14
Program Target Write EEprom:256 of 256
Halt Target 
Run Target 
```
I have built the program and loaded it into Picsimlab without problem, but the thing is when I want to pause the program, step, or anything, picsim gives me this output:
```
Communication error!
```
My question is, is it possible to use the debugger with that version of MPLABX and with mpasm or do you have any suggestion to use mpasm with the plugin? Thanks in advance. Just in case, I will only work with 18f4550.

**Comment by lcgamboa** [comment]
No problem, you are welcome.
The problem you reported actually occurs. PICSimLab has had some updates to the communication protocol and the plugin version 5.30 is not up to date. You can use the latest version 6.05 of the plugin with MPLABX 5.35 and the mpasm assembly debugging will work correctly, I did this test myself. 
Usually it is not necessary to add rules in the firewall because the communication is only local.

Best regards.

**Comment by esbon125** [comment]
It worked perfectly. Thank you for your work.
